### ISSUE TITLE
Why do two secret tokens get generated in the bot framework dashboard?

### ISSUE THREAD

**Issue by theBull** [rockq-org/DirectLineApi#4]
![image](https://cloud.githubusercontent.com/assets/3451643/20987649/58f108fe-bc82-11e6-8c2f-553fab55612a.png)

I'm not sure which secret to use. This might not be the correct place to post this, but would you happen to know?

**Comment by Samurais** [comment]
It is wired, but one may have different clients, so the Botframework may maintain multi tokens for each bot.
